org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
mapping_channel=official
mapping_version=1.20.1
minecraft_version=1.20.1
minecraft_version_range=[1.20.1, 1.21)
forge_version=47.4.1
forge_version_range=[47.1.0,)
loader_version_range=[47,)
mod_id=customized_spice_of_nostalgia
mod_name=Customized: Spice Of Nostalgia
mod_license=MIT
mod_version=1.0a-2025-11-11-U-R
mod_group_id=mangopill.customized_spice_of_nostalgia
mod_authors=Mangopill
mod_credits=Mangopill
mod_description=A lightweight mod that adds an intelligent eating penalty system to the vanilla game, encouraging players to prepare higher-tier foods.
jei_version=15.0.0.12
appleskin_version=mc1.20.1-2.5.1
patchouli_version=1.20.1-84.1
curios_version=5.14.1+1.20.1