@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package mangopill.customized_spice_of_nostalgia.common.core.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;